[tool.poetry]
name = "sky-prj-github-task3"
version = "0.1.0"
description = ""
authors = ["Michael < sorokajr678@bk.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
